### PR TITLE
API documentation

### PR DESCRIPTION
**Pull request by Tiger15cub**
Hi,
i have had a look through the code and documented the API that i saw here.

### CODE REVIEW

**Comment by matteo-convertino** [comment]
I adjusted the table slightly and filled in the "empty" descriptions. I don't do the merge now for the simple fact that in reality it would also be necessary to define what to pass as parameter/body to each API and define the respective return.

**Comment by Tiger15cub** [comment]
Ok, I will work on that when I have some more spare time.

**Comment by Tiger15cub** [comment]
hi @matteo-convertino, i have added some example responces. ill work on the rest now

**Comment by Tiger15cub** [comment]
I have added the rest, and i know there not correct and i do not know how to fix them. (only get requests are correct)

**Pull request closed without merging**
